from rest_framework import serializers
from .models import Blog, Tag

class BlogSerializer(serializers.ModelSerializer):
    # FRONTEND NOTE: Read-Only Fields
    # These are generated by the server. Do NOT send them in a POST request.
    read_time = serializers.ReadOnlyField()
    like_count = serializers.SerializerMethodField()
    author_username = serializers.ReadOnlyField(source='user.username')
    
    # FRONTEND NOTE: Tags Format
    # - SEND: A list of strings
    # - RECEIVE: A list of strings
    tags = serializers.SlugRelatedField(
        many=True, 
        slug_field='name', 
        queryset=Tag.objects.all()
    )

    class Meta:
        model = Blog
        fields = [
            'id',                # Number 
            'title',             # String
            'content',           # String (Markdown or HTML)
            'cover_image',       # URL 
            'user',              # ID (Hidden)
            'author_username',   # String 
            'created_at',        # ISO Date String
            'updated_at',        # ISO Date String
            'read_time',         # Integer (Minutes)
            'like_count',        # Integer
            'category',          # String (Must be one of the CATEGORY_CHOICES)
            'tags'               # Array of Strings
        ]
        read_only_fields = ['user']

    def get_like_count(self, obj):
        return obj.likes.count()