# Generated by Django 5.2.10 on 2026-01-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading_list',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reading_list',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='reading_list',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Reading_List',
        ),
    ]
