# Generated by Django 6.0.1 on 2026-01-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_blog_options_blog_bookmarks_blog_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Culture', 'Culture'), ('Travel', 'Travel'), ('Food', 'Food'), ('Business', 'Business'), ('Tech', 'Tech'), ('Life', 'Life')], default='Life', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='posts.tag'),
        ),
    ]
