# Generated by Django 6.0.1 on 2026-02-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, help_text='A short summary of the blog post.', max_length=500),
        ),
    ]
